### ISSUE TITLE
Tetris Gameplay

### ISSUE THREAD

**Issue by kmeranda** [kmeranda/tetris_wars#3]

**Comment by kforbes** [comment]
Board size is 10x20 squares, and 250x500 pixels.  Each individual square is 25x25 pixels.

**Comment by kforbes** [comment]
Arrays are read `self.array[y][x]` for y in height and x in width

**Comment by kforbes** [comment]
![tetrominoes](https://cloud.githubusercontent.com/assets/10836239/14946117/6e2beaca-0feb-11e6-8ccf-213d297dddde.png)
This is the diagram I'm using as a basis for what our shape configurations should look like/what colors to use.

**Comment by kmeranda** [comment]
For clearing a full row, use `del arr[i]`, where i is the full row that is being deleted. This moves everything above it down an index. Then use `arr.append([0,0,0,0,0,0,0,0,0,0])` to maintain the correct number of rows in the array.

**Comment by kforbes** [comment]
ToDo:
- Delete complete rows
- Losing
- Debug rotate?
